spring.application.name=lore

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/lore_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Gemini API Configuration
gemini.api.key=AIzaSyB_AnLfDi2elp7rBEJjKP-z_4CGQsu7S9U
gemini.api.base-url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
# Logging
logging.level.com.lore.app=DEBUG

# OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
